export const ADMIN_COPY = {
  loginMetaTitle: 'Admin Sign In',
  loginMetaDescription: 'Secure admin access for Avios Support Desk operations.',
  headline: 'Sign in',
  description: 'Enter your credentials to access the operations console.',
  emailLabel: 'Email',
  emailPlaceholder: 'admin@example.com',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  submitCta: 'Sign in',
  submittingCta: 'Signing in…',
  successMessage: 'Signed in successfully.',
  otpTitle: 'Verify your identity',
  otpDescription: 'Enter the 6-digit code sent to',
  otpLabel: 'Verification code',
  otpPlaceholder: '000000',
  otpSubmitCta: 'Verify code',
  otpSubmittingCta: 'Verifying…',
  otpResendCta: 'Resend code',
  otpResendingCta: 'Sending…',
  otpResendWait: 'Resend available in',
  otpSentMessage: 'A verification code was sent.',
  dashboardTitle: 'Overview',
  welcomeTitle: 'Welcome back',
  dashboardGreeting: 'Operations console',
  dashboardDescription: 'Live catalog and system status for Avios Support Desk.',
  dashboardEmailLabel: 'Signed in as',
  brandLabel: 'Avios Support Desk',
  adminRole: 'Admin',
  signOutCta: 'Sign out',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  sessionExpired: 'Your session has expired. Please sign in again.',
  redirecting: 'Checking your session…',
  loadingDashboard: 'Loading dashboard…',
  loadError: 'Unable to load dashboard data.',
  navLabel: 'Admin navigation',
  sidebarTitle: 'Admin',
  statsServices: 'Active services',
  statsServicesTotal: 'total services',
  statsDestinations: 'Destination tiers',
  statsPlaces: 'Active places',
  statsFaqs: 'Active FAQs',
  systemTitle: 'System status',
  databaseLabel: 'Database',
  databaseUp: 'Up',
  databaseDown: 'Down',
  catalogMixTitle: 'Catalog mix',
  catalogMixDescription: 'Share of active content across the public site.',
  catalogBarsTitle: 'Catalog volume',
  catalogBarsDescription: 'Active counts by content type.',
  coverageTitle: 'Coverage overview',
  coverageDescription: 'How catalog depth builds from services to full coverage.',
  chartTotalLabel: 'Total',
  chartEmpty: 'No catalog data available.',
  chartCoverageLabel: 'Count',
  chartServicesShort: 'Services',
  chartDestinationsShort: 'Tiers',
  chartPlacesShort: 'Places',
  chartFaqsShort: 'FAQs',
  chartSeriesServices: 'Services',
  chartSeriesDestinations: 'Tiers',
  chartSeriesPlaces: 'Places',
  chartSeriesCombined: 'All',
  recentServicesTitle: 'Services',
  recentFaqsTitle: 'FAQs',
  emptyServices: 'No active services found.',
  emptyFaqs: 'No active FAQs found.',
  updatedLabel: 'Updated',
  viewAllLabel: 'Live from database',
  servicesTitle: 'Services',
  servicesDescription:
    'Create, edit, reorder, and remove catalog services shown on the public site.',
  servicesLoading: 'Loading services…',
  servicesLoadError: 'Unable to load services.',
  servicesEmpty: 'No services yet. Create the first catalog service.',
  servicesAddCta: 'Add service',
  servicesEditCta: 'Edit',
  servicesDeleteCta: 'Delete',
  servicesMoveUp: 'Move up',
  servicesMoveDown: 'Move down',
  servicesActive: 'Active',
  servicesInactive: 'Inactive',
  servicesOrderLabel: 'Order',
  servicesCreateTitle: 'New service',
  servicesEditTitle: 'Edit service',
  servicesSaveCta: 'Save service',
  servicesSavingCta: 'Saving…',
  servicesCancelCta: 'Cancel',
  servicesCreateSuccess: 'Service created successfully.',
  servicesUpdateSuccess: 'Service updated successfully.',
  servicesDeleteSuccess: 'Service deleted. Catalog order renumbered.',
  servicesDeleteTitle: 'Delete service?',
  servicesDeleteBody:
    'This removes the service from the public site and renumbers remaining services.',
  servicesDeleteConfirm: 'Delete service',
  servicesDeletingCta: 'Deleting…',
  fieldTitle: 'Title',
  fieldSlug: 'Slug',
  fieldTagline: 'Tagline',
  fieldDescription: 'Description',
  fieldFeatures: 'Features',
  fieldFeaturePlaceholder: 'Feature detail',
  fieldAddFeature: 'Add feature',
  fieldRemoveFeature: 'Remove feature',
  fieldIcon: 'Icon',
  fieldImage: 'Preset image fallback',
  fieldImageHint: 'Used on the public site only when no custom media is uploaded.',
  fieldMedia: 'Service media',
  fieldMediaHint: 'Upload a picture (jpeg, png, webp) or short video (mp4, webm).',
  fieldMediaChoose: 'Choose file',
  fieldMediaReplace: 'Replace media',
  fieldMediaRemove: 'Remove media',
  fieldMediaEmpty: 'No custom media uploaded yet.',
  fieldMediaInvalid: 'Choose a jpeg, png, webp, mp4, or webm file.',
  fieldImageAlt: 'Media alt / label',
  fieldActive: 'Visible on public site',
  fieldTitlePlaceholder: 'Flight Booking',
  fieldSlugPlaceholder: 'flights',
  fieldTaglinePlaceholder: 'Short supporting line for the service.',
  fieldDescriptionPlaceholder: 'Full service description shown on the public pages.',
  fieldImageAltPlaceholder: 'Describe the service media for accessibility.',
  servicesMediaUploadSuccess: 'Service media updated.',
  destinationsTitle: 'Destinations',
  destinationsDescription:
    'Create, edit, reorder, and remove destination tiers shown on the public site.',
  destinationsLoading: 'Loading destinations…',
  destinationsLoadError: 'Unable to load destinations.',
  destinationsEmpty: 'No destination tiers yet. Create the first tier.',
  destinationsAddCta: 'Add destination',
  destinationsEditCta: 'Edit',
  destinationsDeleteCta: 'Delete',
  destinationsMoveUp: 'Move up',
  destinationsMoveDown: 'Move down',
  destinationsActive: 'Active',
  destinationsInactive: 'Inactive',
  destinationsCreateTitle: 'New destination',
  destinationsEditTitle: 'Edit destination',
  destinationsSaveCta: 'Save destination',
  destinationsSavingCta: 'Saving…',
  destinationsCancelCta: 'Cancel',
  destinationsCreateSuccess: 'Destination created successfully.',
  destinationsUpdateSuccess: 'Destination updated successfully.',
  destinationsDeleteSuccess: 'Destination deleted. Catalog order renumbered.',
  destinationsDeleteTitle: 'Delete destination?',
  destinationsDeleteBody:
    'This removes the tier and all of its places from the public site, then renumbers remaining tiers.',
  destinationsDeleteConfirm: 'Delete destination',
  destinationsDeletingCta: 'Deleting…',
  fieldDestinationTitlePlaceholder: 'Europe',
  fieldDestinationSlugPlaceholder: 'europe',
  fieldPoints: 'Points',
  fieldPointsPlaceholder: '25000',
  placesTitle: 'Places',
  placesDescription:
    'Create, edit, reorder, and remove destination places within each tier.',
  placesLoading: 'Loading places…',
  placesLoadError: 'Unable to load places.',
  placesEmpty: 'No places yet. Add the first place for a destination tier.',
  placesNeedTier: 'Create a destination tier before adding places.',
  placesAddCta: 'Add place',
  placesEditCta: 'Edit',
  placesDeleteCta: 'Delete',
  placesMoveUp: 'Move up',
  placesMoveDown: 'Move down',
  placesActive: 'Active',
  placesInactive: 'Inactive',
  placesFilterLabel: 'Filter by destination',
  placesFilterAll: 'All destinations',
  placesCreateTitle: 'New place',
  placesEditTitle: 'Edit place',
  placesSaveCta: 'Save place',
  placesSavingCta: 'Saving…',
  placesCancelCta: 'Cancel',
  placesCreateSuccess: 'Place created successfully.',
  placesUpdateSuccess: 'Place updated successfully.',
  placesDeleteSuccess: 'Place deleted. Tier order renumbered.',
  placesDeleteTitle: 'Delete place?',
  placesDeleteBody: 'This removes the place from the public site and renumbers places in its tier.',
  placesDeleteConfirm: 'Delete place',
  placesDeletingCta: 'Deleting…',
  fieldPlaceName: 'Place name',
  fieldPlaceNamePlaceholder: 'Paris',
  fieldPlaceTier: 'Destination tier',
  fieldPlaceTierPlaceholder: 'Select a destination',
  fieldPlaceAlt: 'Image alt text',
  fieldPlaceAltPlaceholder: 'Eiffel Tower at dusk',
  fieldPlaceImageUrl: 'Image URL (optional)',
  fieldPlaceImageUrlPlaceholder: 'https://images.unsplash.com/...',
  fieldPlaceImageUrlHint:
    'Optional fallback when no custom media is uploaded. Use a public HTTPS image URL.',
  fieldPlaceMedia: 'Place media',
  fieldPlaceMediaHint: 'Upload a picture (jpeg, png, webp) or short video (mp4, webm).',
  placesMediaUploadSuccess: 'Place media updated.',
  callbacksTitle: 'Callbacks',
  callbacksDescription:
    'Review callback requests submitted from the public site and update their status.',
  callbacksLoading: 'Loading callback requests…',
  callbacksLoadError: 'Unable to load callback requests.',
  callbacksEmpty: 'No callback requests yet.',
  callbacksFilterLabel: 'Filter by status',
  callbacksFilterAll: 'All statuses',
  callbacksStatusLabel: 'Status',
  callbacksPreferredLabel: 'Preferred call time',
  callbacksSubmittedLabel: 'Submitted',
  callbacksDeleteCta: 'Delete',
  callbacksCancelCta: 'Cancel',
  callbacksUpdateSuccess: 'Callback status updated.',
  callbacksDeleteSuccess: 'Callback request deleted.',
  callbacksDeleteTitle: 'Delete callback request?',
  callbacksDeleteBody: 'This permanently removes the callback request from the admin list.',
  callbacksDeleteConfirm: 'Delete request',
  callbacksDeletingCta: 'Deleting…',
  callbackStatusLabels: {
    new: 'New',
    contacted: 'Contacted',
    closed: 'Closed',
  },
  faqsTitle: 'FAQs',
  faqsDescription:
    'Create, edit, reorder, and remove frequently asked questions shown on the public site.',
  faqsLoading: 'Loading FAQs…',
  faqsLoadError: 'Unable to load FAQs.',
  faqsEmpty: 'No FAQs yet. Create the first question.',
  faqsAddCta: 'Add FAQ',
  faqsEditCta: 'Edit',
  faqsDeleteCta: 'Delete',
  faqsMoveUp: 'Move up',
  faqsMoveDown: 'Move down',
  faqsActive: 'Active',
  faqsInactive: 'Inactive',
  faqsCreateTitle: 'New FAQ',
  faqsEditTitle: 'Edit FAQ',
  faqsSaveCta: 'Save FAQ',
  faqsSavingCta: 'Saving…',
  faqsCancelCta: 'Cancel',
  faqsCreateSuccess: 'FAQ created successfully.',
  faqsUpdateSuccess: 'FAQ updated successfully.',
  faqsDeleteSuccess: 'FAQ deleted. Order renumbered.',
  faqsDeleteTitle: 'Delete FAQ?',
  faqsDeleteBody:
    'This removes the FAQ from the public site and renumbers remaining questions.',
  faqsDeleteConfirm: 'Delete FAQ',
  faqsDeletingCta: 'Deleting…',
  fieldQuestion: 'Question',
  fieldQuestionPlaceholder: 'How do I book a flight by phone?',
  fieldAnswer: 'Answer',
  fieldAnswerPlaceholder: 'Full answer shown in the public FAQ accordion.',
  fieldFaqSlugPlaceholder: 'booking-help',
  settingsTitle: 'Contact',
  settingsDescription:
    'Update the reservation email and contact numbers shown across the public site.',
  settingsLoading: 'Loading contact settings…',
  settingsLoadError: 'Unable to load contact settings.',
  settingsEmailLabel: 'Reservation email',
  settingsEmailPlaceholder: 'reservation@example.com',
  settingsEmailHint: 'This address appears wherever the public site shows the support email.',
  settingsEmailInvalid: 'Enter a valid email address.',
  settingsPhonesLabel: 'Contact numbers',
  settingsPhoneLabel: 'Contact number',
  settingsPhonePlaceholder: '+1 555 000 0000',
  settingsPhonesHint:
    'Add or remove USA/Canada numbers (+1 XXX XXX XXXX). The first number is used for call buttons.',
  settingsAddPhoneCta: 'Add number',
  settingsRemovePhoneCta: 'Remove',
  settingsSaveCta: 'Save contact details',
  settingsSavingCta: 'Saving…',
  settingsUpdateSuccess: 'Contact details updated successfully.',
}

