import {
  ABOUT_PATH,
  BAGGAGE_ASSISTANCE_PATH,
  BLOG_AIRLINE_CONTACT_GUIDE_PATH,
  BLOG_CANCEL_FLIGHT_REFUND_PATH,
  BLOG_CHANGE_FLIGHT_PATH,
  BLOG_DELAY_COMPENSATION_PATH,
  BLOG_PATH,
  BLOG_SAVE_MONEY_FLIGHTS_PATH,
  CANCELLATION_POLICY_PATH,
  CONTACT_PATH,
  COOKIE_POLICY_PATH,
  DESTINATIONS_PATH,
  FLIGHT_BOOKING_PATH,
  FLIGHT_CANCELLATION_PATH,
  FLIGHT_CHANGES_PATH,
  GUIDES_PATH,
  GUIDE_AVION_FLIGHT_BOOKING_PATH,
  GUIDE_AVION_POINTS_VALUE_PATH,
  GUIDE_AVION_REDEMPTION_CHART_PATH,
  GUIDE_AVION_TRANSFER_PARTNERS_PATH,
  GUIDE_BAGGAGE_PATH,
  GUIDE_FLIGHT_BOOKING_PATH,
  GUIDE_FLIGHT_CANCELLATIONS_PATH,
  GUIDE_FLIGHT_CHANGES_PATH,
  GUIDE_POINTS_PATH,
  HILTON_HOTELS_PATH,
  HOME_PATH,
  HOTEL_BOOKING_PATH,
  HOW_IT_WORKS_PATH,
  INDEPENDENT_SERVICE_DISCLOSURE_PATH,
  INTERNATIONAL_FLIGHT_PATH,
  POINTS_REDEMPTION_PATH,
  PRIVACY_POLICY_PATH,
  REFUND_POLICY_PATH,
  SEAT_SELECTION_PATH,
  SERVICE_FEES_PATH,
  SERVICES_PATH,
  TERMS_PATH,
  TOOL_AVION_POINTS_CALCULATOR_PATH,
  TRIP_PLANNING_PATH,
  WYNDHAM_HOTELS_PATH,
} from '@/constants/routes'

/**
 * "Related pages" links per route — 3–5 descriptive anchors each.
 * Guide entries complement each guide's own relatedQuestions instead of repeating them.
 */
export const PAGE_RELATED_LINKS = {
  [ABOUT_PATH]: [
    { href: SERVICES_PATH, label: 'flight and travel services' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: GUIDES_PATH, label: 'travel guides hub' },
  ],
  [CONTACT_PATH]: [
    { href: FLIGHT_BOOKING_PATH, label: 'book flights by phone' },
    { href: FLIGHT_CANCELLATION_PATH, label: 'flight cancellation assistance' },
    { href: SERVICES_PATH, label: 'all travel services' },
    { href: ABOUT_PATH, label: 'about AvioSupportDesk' },
  ],
  [SERVICES_PATH]: [
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: HOTEL_BOOKING_PATH, label: 'hotel booking by phone' },
    { href: WYNDHAM_HOTELS_PATH, label: 'Wyndham hotels booking help' },
    { href: HILTON_HOTELS_PATH, label: 'Hilton hotels booking help' },
    { href: TRIP_PLANNING_PATH, label: 'custom trip planning' },
    { href: CONTACT_PATH, label: 'contact travel support' },
  ],
  [WYNDHAM_HOTELS_PATH]: [
    { href: HILTON_HOTELS_PATH, label: 'Hilton hotels booking help' },
    { href: HOTEL_BOOKING_PATH, label: 'hotel booking by phone' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: INDEPENDENT_SERVICE_DISCLOSURE_PATH, label: 'independent service disclosure' },
  ],
  [HILTON_HOTELS_PATH]: [
    { href: WYNDHAM_HOTELS_PATH, label: 'Wyndham hotels booking help' },
    { href: HOTEL_BOOKING_PATH, label: 'hotel booking by phone' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: INDEPENDENT_SERVICE_DISCLOSURE_PATH, label: 'independent service disclosure' },
  ],
  [FLIGHT_CHANGES_PATH]: [
    { href: GUIDE_FLIGHT_CHANGES_PATH, label: 'airline change fees and rules explained' },
    { href: BLOG_CHANGE_FLIGHT_PATH, label: 'step-by-step flight change walkthrough for 2026' },
    { href: FLIGHT_CANCELLATION_PATH, label: 'cancellation assistance if you cannot rebook' },
    { href: CONTACT_PATH, label: 'contact flight change help' },
  ],
  [FLIGHT_CANCELLATION_PATH]: [
    { href: GUIDE_FLIGHT_CANCELLATIONS_PATH, label: 'refund vs credit rules explained' },
    { href: BLOG_CANCEL_FLIGHT_REFUND_PATH, label: 'how to cancel and request a refund in 2026' },
    { href: FLIGHT_CHANGES_PATH, label: 'change the trip instead of canceling' },
    { href: CONTACT_PATH, label: 'contact cancellation help' },
  ],
  [POINTS_REDEMPTION_PATH]: [
    { href: GUIDE_AVION_FLIGHT_BOOKING_PATH, label: 'how to book flights with Avion points' },
    { href: TOOL_AVION_POINTS_CALCULATOR_PATH, label: 'Avion points value calculator' },
    { href: GUIDE_AVION_POINTS_VALUE_PATH, label: 'what Avion points are worth' },
    { href: SERVICE_FEES_PATH, label: 'how assistance fees are quoted' },
  ],
  [HOTEL_BOOKING_PATH]: [
    { href: WYNDHAM_HOTELS_PATH, label: 'Wyndham hotels booking help' },
    { href: HILTON_HOTELS_PATH, label: 'Hilton hotels booking help' },
    { href: CONTACT_PATH, label: 'contact hotel booking help' },
    { href: TRIP_PLANNING_PATH, label: 'custom trip planning' },
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
  ],
  [DESTINATIONS_PATH]: [
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: INTERNATIONAL_FLIGHT_PATH, label: 'international flights by phone' },
    { href: TRIP_PLANNING_PATH, label: 'multi-city trip planning' },
    { href: CONTACT_PATH, label: 'contact destination specialists' },
  ],
  [INTERNATIONAL_FLIGHT_PATH]: [
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: TRIP_PLANNING_PATH, label: 'custom trip planning' },
    { href: BAGGAGE_ASSISTANCE_PATH, label: 'baggage allowance help' },
    { href: CONTACT_PATH, label: 'contact international flight help' },
    { href: DESTINATIONS_PATH, label: 'popular flight destinations' },
  ],
  [GUIDES_PATH]: [
    { href: GUIDE_FLIGHT_BOOKING_PATH, label: 'how to book a flight by phone' },
    { href: GUIDE_AVION_FLIGHT_BOOKING_PATH, label: 'Avion points flight booking guide' },
    { href: GUIDE_POINTS_PATH, label: 'points and miles travel guide' },
    { href: POINTS_REDEMPTION_PATH, label: 'points redemption assistance' },
    { href: TOOL_AVION_POINTS_CALCULATOR_PATH, label: 'Avion points value calculator' },
  ],
  [GUIDE_FLIGHT_BOOKING_PATH]: [
    { href: INTERNATIONAL_FLIGHT_PATH, label: 'booking international flights by phone' },
    { href: GUIDE_BAGGAGE_PATH, label: 'carry-on and checked bag rules' },
    { href: SEAT_SELECTION_PATH, label: 'choosing seats before you fly' },
    { href: BLOG_SAVE_MONEY_FLIGHTS_PATH, label: 'ways to lower your airfare' },
    { href: TRIP_PLANNING_PATH, label: 'planning a multi-city itinerary' },
  ],
  [GUIDE_FLIGHT_CHANGES_PATH]: [
    { href: FLIGHT_CHANGES_PATH, label: 'get flight change help by phone' },
    { href: BLOG_CHANGE_FLIGHT_PATH, label: 'step-by-step flight change walkthrough for 2026' },
    { href: BLOG_DELAY_COMPENSATION_PATH, label: 'rights after delays and missed connections' },
    { href: GUIDE_FLIGHT_BOOKING_PATH, label: 'booking a replacement flight by phone' },
  ],
  [GUIDE_FLIGHT_CANCELLATIONS_PATH]: [
    { href: FLIGHT_CANCELLATION_PATH, label: 'get cancellation assistance by phone' },
    { href: BLOG_CANCEL_FLIGHT_REFUND_PATH, label: 'how to cancel and request a refund in 2026' },
    { href: BLOG_DELAY_COMPENSATION_PATH, label: 'compensation when the airline disrupts your trip' },
    { href: REFUND_POLICY_PATH, label: 'refunds of our assistance fee' },
  ],
  [GUIDE_BAGGAGE_PATH]: [
    { href: SEAT_SELECTION_PATH, label: 'seat selection help by phone' },
    { href: INTERNATIONAL_FLIGHT_PATH, label: 'international flights booked by phone' },
    { href: BLOG_SAVE_MONEY_FLIGHTS_PATH, label: 'avoiding surprise bag fees' },
    { href: GUIDE_FLIGHT_CHANGES_PATH, label: 'airline change rules explained' },
  ],
  [GUIDE_POINTS_PATH]: [
    { href: GUIDE_AVION_TRANSFER_PARTNERS_PATH, label: 'how Avion partner transfers work' },
    { href: GUIDE_AVION_POINTS_VALUE_PATH, label: 'what Avion points are worth' },
    { href: HOW_IT_WORKS_PATH, label: 'how independent booking help works' },
    { href: GUIDES_PATH, label: 'all travel guides' },
  ],
  [GUIDE_AVION_FLIGHT_BOOKING_PATH]: [
    { href: POINTS_REDEMPTION_PATH, label: 'paid help comparing Avion redemptions' },
    { href: TOOL_AVION_POINTS_CALCULATOR_PATH, label: 'compare cash and points with the calculator' },
    { href: GUIDE_AVION_POINTS_VALUE_PATH, label: 'worked Avion points value examples' },
    { href: SERVICE_FEES_PATH, label: 'how assistance fees are quoted' },
  ],
  [GUIDE_AVION_REDEMPTION_CHART_PATH]: [
    { href: POINTS_REDEMPTION_PATH, label: 'help comparing chart and portal prices' },
    { href: GUIDE_AVION_TRANSFER_PARTNERS_PATH, label: 'Avion partner transfer rules' },
    { href: INDEPENDENT_SERVICE_DISCLOSURE_PATH, label: 'our independence from Avion Rewards' },
    { href: GUIDES_PATH, label: 'all travel guides' },
  ],
  [GUIDE_AVION_POINTS_VALUE_PATH]: [
    { href: TOOL_AVION_POINTS_CALCULATOR_PATH, label: 'run the Avion points value calculator' },
    { href: GUIDE_AVION_FLIGHT_BOOKING_PATH, label: 'booking flights with Avion points' },
    { href: POINTS_REDEMPTION_PATH, label: 'independent help weighing a redemption' },
    { href: SERVICE_FEES_PATH, label: 'travel assistance fees' },
  ],
  [GUIDE_AVION_TRANSFER_PARTNERS_PATH]: [
    { href: GUIDE_AVION_POINTS_VALUE_PATH, label: 'what Avion points are worth' },
    { href: TOOL_AVION_POINTS_CALCULATOR_PATH, label: 'Avion points value calculator' },
    { href: HOW_IT_WORKS_PATH, label: 'how independent booking help works' },
    { href: GUIDE_POINTS_PATH, label: 'points and miles basics for flights' },
  ],
  [TOOL_AVION_POINTS_CALCULATOR_PATH]: [
    { href: GUIDE_AVION_POINTS_VALUE_PATH, label: 'what Avion points are worth, with worked examples' },
    { href: GUIDE_AVION_REDEMPTION_CHART_PATH, label: 'Avion points redemption chart' },
    { href: GUIDE_POINTS_PATH, label: 'points and miles travel guide' },
    { href: POINTS_REDEMPTION_PATH, label: 'independent help with a redemption' },
    { href: SERVICE_FEES_PATH, label: 'travel assistance fees' },
  ],
  [BLOG_PATH]: [
    { href: BLOG_CANCEL_FLIGHT_REFUND_PATH, label: 'how to cancel a flight and get a refund' },
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: FLIGHT_CANCELLATION_PATH, label: 'flight cancellation assistance' },
    { href: GUIDES_PATH, label: 'travel guides hub' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
  ],
  [BLOG_CANCEL_FLIGHT_REFUND_PATH]: [
    { href: GUIDE_FLIGHT_CANCELLATIONS_PATH, label: 'refund vs credit rules explained' },
    { href: FLIGHT_CANCELLATION_PATH, label: 'cancellation assistance by phone' },
    { href: GUIDE_FLIGHT_CHANGES_PATH, label: 'change fees as an alternative to canceling' },
    { href: CANCELLATION_POLICY_PATH, label: 'cancellation policy for bookings we assist with' },
  ],
  [BLOG_CHANGE_FLIGHT_PATH]: [
    { href: GUIDE_FLIGHT_CHANGES_PATH, label: 'airline change fees and rules explained' },
    { href: FLIGHT_CHANGES_PATH, label: 'flight change assistance by phone' },
    { href: GUIDE_FLIGHT_CANCELLATIONS_PATH, label: 'refund vs credit rules if you cancel' },
    { href: GUIDE_FLIGHT_BOOKING_PATH, label: 'booking a replacement flight by phone' },
  ],
  [BLOG_DELAY_COMPENSATION_PATH]: [
    { href: GUIDE_FLIGHT_CANCELLATIONS_PATH, label: 'refunds when the airline cancels' },
    { href: GUIDE_FLIGHT_CHANGES_PATH, label: 'change rules after a schedule disruption' },
    { href: TRIP_PLANNING_PATH, label: 'planning connections with realistic buffers' },
  ],
  [BLOG_AIRLINE_CONTACT_GUIDE_PATH]: [
    { href: INDEPENDENT_SERVICE_DISCLOSURE_PATH, label: 'how we differ from airline support' },
    { href: HOW_IT_WORKS_PATH, label: 'how independent booking help works' },
    { href: SERVICE_FEES_PATH, label: 'what our assistance fee covers' },
    { href: GUIDES_PATH, label: 'plain-language airline guides' },
  ],
  [BLOG_SAVE_MONEY_FLIGHTS_PATH]: [
    { href: GUIDE_FLIGHT_BOOKING_PATH, label: 'what to prepare before booking by phone' },
    { href: GUIDE_BAGGAGE_PATH, label: 'carry-on and checked bag fee rules' },
    { href: GUIDE_POINTS_PATH, label: 'when cash beats points on flights' },
    { href: FLIGHT_BOOKING_PATH, label: 'compare fares with a booking specialist' },
  ],
  [SERVICE_FEES_PATH]: [
    { href: HOW_IT_WORKS_PATH, label: 'how it works' },
    { href: INDEPENDENT_SERVICE_DISCLOSURE_PATH, label: 'independent service disclosure' },
    { href: POINTS_REDEMPTION_PATH, label: 'points redemption assistance' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
    { href: TERMS_PATH, label: 'terms and conditions' },
  ],
  [HOW_IT_WORKS_PATH]: [
    { href: SERVICE_FEES_PATH, label: 'service fees' },
    { href: INDEPENDENT_SERVICE_DISCLOSURE_PATH, label: 'independent service disclosure' },
    { href: POINTS_REDEMPTION_PATH, label: 'Avion points booking assistance' },
    { href: FLIGHT_BOOKING_PATH, label: 'flight booking assistance' },
    { href: GUIDES_PATH, label: 'travel guides hub' },
    { href: CONTACT_PATH, label: 'contact travel support' },
  ],
  [INDEPENDENT_SERVICE_DISCLOSURE_PATH]: [
    { href: SERVICE_FEES_PATH, label: 'service fees' },
    { href: HOW_IT_WORKS_PATH, label: 'how it works' },
    { href: ABOUT_PATH, label: 'about AvioSupportDesk' },
    { href: TERMS_PATH, label: 'terms and conditions' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
  ],
  [PRIVACY_POLICY_PATH]: [
    { href: TERMS_PATH, label: 'terms and conditions' },
    { href: COOKIE_POLICY_PATH, label: 'cookie policy' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
    { href: HOME_PATH, label: 'AvioSupportDesk home' },
  ],
  [CANCELLATION_POLICY_PATH]: [
    { href: FLIGHT_CANCELLATION_PATH, label: 'flight cancellation assistance' },
    { href: REFUND_POLICY_PATH, label: 'refund policy' },
    { href: CONTACT_PATH, label: 'contact travel support' },
    { href: SERVICES_PATH, label: 'all travel services' },
  ],
  [TERMS_PATH]: [
    { href: PRIVACY_POLICY_PATH, label: 'privacy policy' },
    { href: REFUND_POLICY_PATH, label: 'refund policy' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
    { href: ABOUT_PATH, label: 'about AvioSupportDesk' },
  ],
  [REFUND_POLICY_PATH]: [
    { href: FLIGHT_CANCELLATION_PATH, label: 'flight cancellation assistance' },
    { href: CANCELLATION_POLICY_PATH, label: 'cancellation policy' },
    { href: CONTACT_PATH, label: 'contact refund help' },
    { href: HOME_PATH, label: 'AvioSupportDesk home' },
  ],
  [COOKIE_POLICY_PATH]: [
    { href: PRIVACY_POLICY_PATH, label: 'privacy policy' },
    { href: TERMS_PATH, label: 'terms and conditions' },
    { href: CONTACT_PATH, label: 'contact AvioSupportDesk' },
    { href: HOME_PATH, label: 'AvioSupportDesk home' },
  ],
}

export function getPageRelatedLinks(path) {
  return PAGE_RELATED_LINKS[path]
}
