export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_422',
  NOT_FOUND: 'RESOURCE_404',
  SERVICE_NOT_FOUND: 'SERVICE_404',
  DESTINATION_NOT_FOUND: 'DESTINATION_404',
  FAQ_NOT_FOUND: 'FAQ_404',
  CONFLICT: 'RESOURCE_409',
  RATE_LIMITED: 'RATE_429',
  INTERNAL: 'INTERNAL_500',
  DATABASE: 'DATABASE_500',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
