export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_422',
  SERVICE_NOT_FOUND: 'SERVICE_404',
  SERVICE_SLUG_CONFLICT: 'SERVICE_409',
  DESTINATION_NOT_FOUND: 'DESTINATION_404',
  DESTINATION_SLUG_CONFLICT: 'DESTINATION_409',
  PLACE_NOT_FOUND: 'PLACE_404',
  CALLBACK_NOT_FOUND: 'CALLBACK_404',
  FAQ_NOT_FOUND: 'FAQ_404',
  FAQ_SLUG_CONFLICT: 'FAQ_409',
  AUTH_INVALID: 'AUTH_401',
  AUTH_EXPIRED: 'AUTH_401_EXPIRED',
  AUTH_PIN_INVALID: 'AUTH_PIN_401',
  AUTH_PIN_EXPIRED: 'AUTH_PIN_401_EXPIRED',
  AUTH_PIN_LOCKED: 'AUTH_PIN_429',
  AUTH_NOT_CONFIGURED: 'AUTH_503',
  RATE_LIMITED: 'RATE_429',
  INTERNAL: 'INTERNAL_500',
  DATABASE: 'DATABASE_500',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
